Fix (?) PyPI barfing on readme.
setup.py directly concatenates the README.rst and CHANGELOG.rst files,
causing

c:\work\github\virtualenvwrapper-win> python setup.py checkdocs
running checkdocs
<string>:154: (ERROR/3) Unexpected indentation.
error: long_description had reST syntax errors

I fixed (?) this by adding a newline in setup.py, and introducing a
comment and a header in CHANGELOG.rst.

I used `python setup.py check --restructuredtext`  (found at
https://stackoverflow.com/a/44186594/75103) to check.